import '@/assets/images/home-o.png'
import '@/assets/images/home.png'
import '@/assets/images/mine-o.png'
import '@/assets/images/mine.png'
import '@/assets/images/b-baidu.png'
import '@/assets/images/b-weibo.jpg'
import '@/assets/images/b-douyin.png'
